name: CI

run-name: "CI by 24f1002007@ds.study.iitm.ac.in (${{ github.actor }})"  # Dynamic!
# Add this line!

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo "Tests passed!"
